# Application Configuration
spring:
  application:
    name: ${APP_NAME:spaced-repetition}
  
  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spaced_repetition?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
        jdbc:
          time_zone: ${DB_TIMEZONE:UTC}
        validator:
          apply_to_ddl: false

# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# Security Configuration
app:
  security:
    jwt:
      secret: ${JWT_SECRET:default-secret-key-change-in-production}
      expiration: ${JWT_EXPIRATION:86400000}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
      allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
      allowed-headers: ${CORS_ALLOWED_HEADERS:*}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

# Logging Configuration
logging:
  level:
    org.aibles.spaced_repetition: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# External Services Configuration
external:
  email:
    smtp:
      host: ${EMAIL_SMTP_HOST:smtp.gmail.com}
      port: ${EMAIL_SMTP_PORT:587}
      username: ${EMAIL_SMTP_USERNAME:}
      password: ${EMAIL_SMTP_PASSWORD:}
      auth: ${EMAIL_SMTP_AUTH:true}
      starttls:
        enable: ${EMAIL_SMTP_STARTTLS:true}
  
  file:
    upload:
      path: ${FILE_UPLOAD_PATH:./uploads}
      max-size: ${FILE_MAX_SIZE:10MB}
      allowed-types: ${FILE_ALLOWED_TYPES:jpg,jpeg,png,gif,pdf}

# API Configuration
api:
  rate-limit:
    requests-per-minute: ${RATE_LIMIT_RPM:100}
    burst-capacity: ${RATE_LIMIT_BURST:200}
  
  pagination:
    default-page-size: ${PAGINATION_DEFAULT_SIZE:20}
    max-page-size: ${PAGINATION_MAX_SIZE:100}